### ISSUE TITLE
just a question, why my page apears in the source code? 

### ISSUE THREAD

**Issue by ankris812** [22i/22i.github.io#1]
my website its literally empty.

**Comment by 22i** [comment]
The first button on the website is [I'm Feeling Lucky](https://22i.github.io/lucky.github.io.page.html)

which gets you to one randomly picked github.io page

every so often i search for github.io pages. The ones i find get added to the [masterlist](https://raw.githubusercontent.com/22i/22i.github.io/master/content/scripts/grab_io_pages/masterlist.txt) with at least 370000 github.io pages. Thus your page by chance got there.

Some of them are empty but you never know what you might find
